### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (void-function marginalia--orig-completion-metadata-get)

### ISSUE THREAD

**Issue by zenny** [pprevos/emacs-writing-studio#11]
Hi,

After upgrading to the latest configs, I am getting:

```
No packages to upgrade
Error in post-command-hook (vertico--exhibit): (void-function marginalia--orig-completion-metadata-get)
Quit
```

Both `vertico` and `marginalia` have been upgraded to latest release, fyi.
 
Also raised the issue in https://github.com/minad/vertico/discussions/505.
It could either be a `vertico` or `marginalia` which might have been deprecated?!

Cheers,

**Comment by pprevos** [comment]
Hi,

Daniel Mendler manages both Vertic and Marginalia. Both packages are very much alive (judged by recent commits).

I just did a fresh install (clone the repo and use `emacs --init-directory emacs-wring-studio` and get no compilation errors. 

I use EndeavourOS (Arch Linux) and the `emacs-nativecomp` version.

P:)

**Comment by zenny** [comment]
> Hi,
> 
> Daniel Mendler manages both Vertic and Marginalia. Both packages are very much alive (judged by recent commits).
> 
> I just did a fresh install (clone the repo and use `emacs --init-directory emacs-wring-studio`) and get no compilation errors.
> 
> I use EndeavourOS (Arch Linux) and the `emacs-nativecomp` version.
> 
> P:)

I just restarted emacs after upgrading all the packages. Post restart, the error message went away except the menu minibuffer appear at the bottom instead of the side.

Thanks.
