### ISSUE TITLE
openwith-file-handler issue with external program

### ISSUE THREAD

**Issue by zenny** [pprevos/emacs-writing-studio#12]
Hi @pprevos:

Whenever I tried to open any pdf files, it neither opens with the external app. Shows up with a message:

```
openwith-file-handler: Opened 00-emacs-writing-studio-review-harald-kirsch.pdf in external program
```
but it does not open anywhere (zathura is my default pdf-viewer in the system)!

Thanks!

**Comment by zenny** [comment]
Hi again,

I have even tried to install `pdf-tools` to open pdfs internally with following snippets, but no go:

```
(use-package pdf-tools
  :magic ("%PDF" . pdf-view-mode)
  :init (pdf-tools-install :no-query))

(use-package pdf-view
  :ensure nil
  :after pdf-tools
  :bind (:map pdf-view-mode-map
              ("C-s" . isearch-forward)
              ("d" . pdf-annot-delete)
              ("h" . pdf-annot-add-highlight-markup-annotation)
              ("t" . pdf-annot-add-text-annotation))
  :custom
  (pdf-view-display-size 'fit-page)
  (pdf-view-resize-factor 1.1)
  ;; Avoid searching for unicodes to speed up pdf-tools.
  (pdf-view-use-unicode-ligther nil)
  ;; Enable HiDPI support, at the cost of memory.
  (pdf-view-use-scaling t))
```

Any input? Thanks.

**Comment by zenny** [comment]
Hi @pprevos,

I partial solved to open the files with the external programs, it was not happening because the `(openwith-association nil))` was declared.

As per the `openwith` documentation (https://github.com/garberw/openwith), it worked after appending the following,

```
(when (require 'openwith nil 'noerror)
  (setq openwith-associations
        (list
         (list (openwith-make-extension-regexp
                '("mpg" "mpeg" "mp3" "mp4"
                  "avi" "wmv" "wav" "mov" "flv"
                  "ogm" "ogg" "mkv"))
               "mpv"
               '(file))
         (list (openwith-make-extension-regexp
                '("xbm" "pbm" "pgm" "ppm" "pnm"
                  "png" "gif" "bmp" "tif" "jpeg" "jpg"))
               "geeqie"
               '(file))
         (list (openwith-make-extension-regexp
                '("doc" "xls" "ppt" "odt" "ods" "odg" "odp"))
               "libreoffice"
               '(file))
         '("\\.lyx" "lyx" (file))
         '("\\.chm" "kchmviewer" (file))
         (list (openwith-make-extension-regexp
                '("pdf" "ps" "ps.gz" "dvi"))
               "okular"
               '(file))
         ))
    (openwith-mode 1))
```

However, I am yet to figure out how to open it internally inside emacs with `pdf-tools`!?

**Comment by pprevos** [comment]
Hi @zenny,

Do you need to configure `pdf-view`? Try this:

``` elisp
(use-package pdf-tools
  :magic ("%PDF" . pdf-view-mode)
  :init (pdf-tools-install :no-query)
  :bind (:map pdf-view-mode-map
              ("C-s" . isearch-forward)
              ("d" . pdf-annot-delete)
              ("h" . pdf-annot-add-highlight-markup-annotation)
              ("t" . pdf-annot-add-text-annotation))
  :custom
  (pdf-view-display-size 'fit-page)
  (pdf-view-resize-factor 1.1)
  ;; Avoid searching for unicodes to speed up pdf-tools.
  (pdf-view-use-unicode-ligther nil)
  ;; Enable HiDPI support, at the cost of memory.
  (pdf-view-use-scaling t))
```

**Comment by zenny** [comment]
> Hi @zenny,
> 
> Do you need to configure `pdf-view`? Try this:
> 
> ```emacs-lisp
> (use-package pdf-tools
>   :magic ("%PDF" . pdf-view-mode)
>   :init (pdf-tools-install :no-query)
>   :bind (:map pdf-view-mode-map
>               ("C-s" . isearch-forward)
>               ("d" . pdf-annot-delete)
>               ("h" . pdf-annot-add-highlight-markup-annotation)
>               ("t" . pdf-annot-add-text-annotation))
>   :custom
>   (pdf-view-display-size 'fit-page)
>   (pdf-view-resize-factor 1.1)
>   ;; Avoid searching for unicodes to speed up pdf-tools.
>   (pdf-view-use-unicode-ligther nil)
>   ;; Enable HiDPI support, at the cost of memory.
>   (pdf-view-use-scaling t))
> ```

Thanks for your input. Yet the snippets did not make any difference to get the pdf file with pdf-tools, fyi. Thanks

**Comment by pprevos** [comment]
Hi Zenny, sorry I cannot help you further. This config works seamlessly on my system (EndeavourOS with `emacs-nativecomp` installed).

Also, `pdf-tools` is not part of Emacs Writing Studio because of its complexities.

**Comment by zenny** [comment]
> Hi Zenny, sorry I cannot help you further. This config works seamlessly on my system (EndeavourOS with `emacs-nativecomp` installed).
> 
> Also, `pdf-tools` is not part of Emacs Writing Studio because of its complexities.

I pulled your repo once again and launched emacs with the `pdf-tools`-related snippet and it works. Thanks for the pointer. Cheers,
