### ISSUE TITLE
Error running timer ‘which-key--update’: (error "#<window 119> is not a live window")

### ISSUE THREAD

**Issue by zenny** [pprevos/emacs-writing-studio#13]
Hi,

When I try to use `C-h k` to use `helpful`, instead of showing up the the minibuffer, it shows an error:

```
Error running timer ‘which-key--update’: (error "#<window 119> is not a live window")
```

Thanks.

**Comment by pprevos** [comment]
Hi @zenny,

I need more information to be able to replicate the error. Everything works fine on my system.

P:)

**Comment by zenny** [comment]
> Hi @zenny,
> 
> I need more information to be able to replicate the error. Everything works fine on my system.
> 
> P:)

Hi @pprevos:

I get something like below when I press `C-h k`:

```
Error running timer ‘which-key--update’: (error "#<window 503> is not a live window")
uncompressing org.el.gz...done
Note: file is write protected
uncompressing org.el.gz...done
Searched 0/1 files
Searched 1/1 files
Marking matching files...
3 matching files marked
Hid 3 dotfiles.
Beginning of buffer [8 times]
Error running timer ‘which-key--update’: (error "#<window 515> is not a live window")
uncompressing help-fns.el.gz...done
Note: file is write protected
uncompressing help-fns.el.gz...done
```

I am running on Voidlinux, Emacs v29.4, and orgmode v9.6.15, fyi.

Hats off to you for developing a wonderful documentation I am cherishing.  Kudos to you.

**Comment by pprevos** [comment]
I am glad you like the EWS book.

These comments are interesting: "Note: file is write protected"

Did you compile Emacs yourself?

**Comment by zenny** [comment]
> I am glad you like the EWS book.

I am cherishing reading the book, indeed. Maybe both of us have a similar academic background, hobbies (magic) and intention to help it seems to me.

> 
> These comments are interesting: "Note: file is write protected"

That is pretty strange to me, too as I am running your repo with:

`emacs --debug-init --init-dir=/path/to/ews-repo`
> 
> Did you compile Emacs yourself?

Nope, it is upstream from voidlinux repo.

**Comment by pprevos** [comment]
This error seems to relate to new popup windows. Not sure where that comes from. Can you try running `(which-key-setup-minibuffer)`?

**Comment by zenny** [comment]
> This error seems to relate to new popup windows. Not sure where that comes from. Can you try running `(which-key-setup-minibuffer)`?

When `M-x which-key-setup-minibuffer` is executed, there is nothing appears in any minibuffer/buffer, but only reports:

```
Error running timer ‘which-key--update’: (error "#<window 1000> is not a live window")
Mark set
Wrote /home/zenny/.ihsec/ews/recentf
Mark set
You can run the command ‘which-key-setup-minibuffer’ with M-x -setup-m
Beginning of buffer [7 times]
C-x <mouse-1> is undefined
End of buffer
Mark set
```

**Comment by pprevos** [comment]
I cannot replicate these errors. Can you run `toggle-debug-on-error` and see what the output is.

It will tell you which function / package is causing the grieve.

**Comment by zenny** [comment]
@pprevos I come to know that the `dired-sidebar` is the culprit as you have stated. Disabling the package went well with your config. Sorry for the false alarm here. Thanks
