### ISSUE TITLE
I can´t view pdf files

### ISSUE THREAD

**Issue by quijote-asim** [pprevos/emacs-writing-studio#16]
Good morning, sorry if the question is too obvious, but I can't find a solution.

﻿I have a newly installed system (Arch/Xfce) and I can't get Emacs, with the EWS init to open a PDF file, it always gives me this message:

﻿**openwith-file-handler: <file-name>.pdf in external program.**

﻿The required programs are all installed.

Now I don't have my desktop computer at hand, on which Emacs opens PDFs without problems, so I can't compare.

What could be my mistake?

**Comment by pprevos** [comment]
There was a bug with the `openwith` package. I just committed a new version.

Alternatively change the following line i your config:

`(openwith-association nil))`

to

`(openwith-associations nil))`

Look forward to you

Hope this fixes it.

**Comment by quijote-asim** [comment]
Ok, fixed.
Thanks

**Comment by zenny** [comment]
> There was a bug with the `openwith` package. I just committed a new version.
> 
> Alternatively change the following line i your config:
> 
> `(openwith-association nil))`
> 
> to
> 
> `(openwith-associations nil))`
> 
> Look forward to you
> 
> Hope this fixes it.

I have:

```
(use-package openwith
  :config
  (openwith-mode t)
  :custom
  (openwith-associations nil))
```

Yet it does not open PDFs in the system-default pdf viewer, despite not loading the pdf-tools related snippets. Rest of the codes are EWS-default, fyi.

**Comment by pprevos** [comment]
`(openwith-associations nil)` erases the package defaults because they might not make sense for everybody.

You need to set this variable to include your favourite PDF reader. The package does not recognise system defaults. The book has some suggestions or see https://github.com/garberw/openwith.

Great question, I'll clarify in the book.

**Comment by zenny** [comment]
> `(openwith-associations nil)` erases the package defaults because they might not make sense for everybody.
> 
> You need to set this variable to include your favourite PDF reader. The package does not recognise system defaults. The book has some suggestions or see https://github.com/garberw/openwith.
> 
> Great question, I'll clarify in the book.

I had a notion that `openwith` detects the system default applications. Anyway, I did exactly as we have discussed earlier in https://github.com/pprevos/emacs-writing-studio/issues/12#issuecomment-2245899481.

Anyway. Thanks and have a nice weekend.
