### ISSUE TITLE
I can't write after insert a link.

### ISSUE THREAD

**Issue by quijote-asim** [pprevos/emacs-writing-studio#19]
I am observing a behavior that I don't know if it comes from DENOTE, although it seems to me more a problem of the Org Mode settings of EWS.

When I am writing a note and insert a link, when I try to continue writing I get this message:

`user-error: Editing in invisible areas is prohibited, make them visible first`

As far as I am able to figure out, I think the dot is in the hidden parentheses of the link.

Is this my mistake, and is there an easy way to fix it?

**Comment by pprevos** [comment]
This error usually has to do with folded Org text (subtrees, drawers or other blocks).

What if you change the `org-fold-catch-invisible-edits` variable to `'show`?

**Comment by quijote-asim** [comment]
> This error usually has to do with folded Org text (subtrees, drawers or other blocks).
> 
> What if you change the `org-fold-catch-invisible-edits` variable to `'show`?

Perfect that solves the problem, thanks once again.

**Comment by pprevos** [comment]
Excellent. I have added this to the EWS config.
