### ISSUE TITLE
Is this for Linux or Windows?

### ISSUE THREAD

**Issue by OrionRandD** [pprevos/emacs-writing-studio#22]
Hi,
Is EWS for Linux or Windows?
I mean: if I clone your repo on Windows/Linux, will it work?
Could you add more details to your README file explaining this question?
The reason I am asking this is that I'd like to teach Emacs for Windows users...
But, Emacs is not a very integrated environment on a Windows box :( 

I have a suggestion to this article:
https://lucidmanager.org/productivity/getting-started-with-emacs/

1. Refer to Viper-mode as a native Emacs built-in function for Vimers (in case one does not want to install the Evil-mode beast)

3. Try youself to use Stumpwm WM, instead of I3WM (Some years ago I was a i3wm and xmonad user, but for years I have been using Stumpwm because it was written for Emacs users)
4. see here:

;;  StumpWM

;;  Official website
;;  https://stumpwm.github.io/

;;  The stumpwm experience  
;;  https://www.youtube.com/watch?v=tKt_rVO960Q

;;  The stumpwm experience - modern version
;;  https://www.youtube.com/watch?v=TdA6t6sLWQY

;;  Leaving dwm for StumpWM
;;  https://www.youtube.com/watch?v=TdQdBQu3fFM

;;  Wiki:
;;  github.com/stumpwm/stumpwm/wiki

;;  Manual 
;;  stumpwm.github.io/git/stumpwm-git.pdf

;;  Mailing List:
;;  lists.nongnu.org/mailman/listinfo/stumpwm-devel

;;  Additional Modules:
;;  github.com/stumpwm/stumpwm-contrib

;;  Gavinok Config:
;;  github.com/Gavinok/stump-conf

Thx a lot.

**Comment by pprevos** [comment]
Hi @OrionRandD ,

Being Emacs, the configuration is independent of the operating system. I have added some clarifications to the Getting Started and Readme pages.

The main difference between Linux / MacOs or Windows are the supporting applications. If you have experience with Windows, then perhaps you can help get this page accurate: https://lucidmanager.org/productivity/emacs-windows/

Thanks for the StumpWM tip. I am fine with i3wm - my issues with it are less then the effort to migrate to a new one.

Readme page updated: [20dbbba](https://github.com/pprevos/emacs-writing-studio/commit/20dbbba92aa78c8a811e243faa430e5f3f3aa83f)

P:)
