### ISSUE TITLE
(reading) Office file support is not provided by ox-odt

### ISSUE THREAD

**Issue by telenieko** [pprevos/emacs-writing-studio#23]
Hi,

Thank you for EWS. Looks like it can become a promising resource for learning Emacs next to [Mastering Emacs](https://www.masteringemacs.org/)!

On [your webiste](https://lucidmanager.org/productivity/reading-ebooks-with-emacs/) and in the code here:

https://github.com/pprevos/emacs-writing-studio/blob/20dbbba92aa78c8a811e243faa430e5f3f3aa83f/init.el#L304-L314

`ox-odt` is added as if it provides Office file reading support. But, does it? Isn't `ox-odt` an exporter only?

Looking at doc-view code it would appear that no extra packages are needed for such support. Only doc-view & the soffice binary.

So this should suffice:

```emacs-lisp
(use-package doc-view
  :ensure nil				; builtin
  :mode
  ("\\.\\(?:OD[CFIGPST]\\|od[cfigpst]\\)\\'" . doc-view-mode-maybe) ; Also, make sure you have the `soffice' binary in $PATH.
  :custom
  (doc-view-mupdf-use-svg (image-type-available-p 'svg)))
```
(the SVG bit being only for Emacs >29.1; note that the auto-mode-list can also be managed with special use-package keywords)

**Comment by pprevos** [comment]
Hi,

Your version is perhaps a more precise way of setting this up. My version works but is indeed a bit clumsy.

When trying this on vanilla Emacs, It seems that the bug was fixed with Emacs 29.4, so perhaps the whole line is line might be unnecessary

P:)
