### ISSUE TITLE
Missing packages after start

### ISSUE THREAD

**Issue by LukasCBossert** [pprevos/emacs-writing-studio#5]
Hi, when I start EWS with `emacs --init-directory <..../emacs-writing-studio>` I get the following error-message:

```
: Missing executable files(s): exiftool, ddjvu
```

**Comment by pprevos** [comment]
Hi Lukas,

exiftool is not a requirement (yet), I'll remove that warning.

ddjvu is required for reading DjVu ebooks, so if it is missing that is the only functionality missing.

**Comment by pprevos** [comment]
Fixed in [e500e4b](https://github.com/pprevos/emacs-writing-studio/commit/e500e4b39970f30f3fe5a759bdc0a5624a368a29)
