### ISSUE TITLE
Missing executables files

### ISSUE THREAD

**Issue by EvanMath** [pprevos/emacs-writing-studio#7]
Hey there,

I have installed Emacs 29 in WSL2 and used your configuration. Everything runs fine but I am getting the following message in opening:
"Missing executable files(s): pdftotext, (gs or mutool), hunspell, latex, (convert or gm), dot, dvipng, ddjvu, pdftotext, zip, soffice"...

Am I supposed to install somehow all these packages in WSL2?

**Comment by pprevos** [comment]
Hi Evenmath,

This is a yet to be documented feature (I am working on an Emacs Writing Studio book).

These applications are needed for various tasks

I have never used WSL2.

Does `sudo apt install hunspell` work?

**Comment by pprevos** [comment]
These are packages within other software. The new README file in this repository explains it in more detail.

I have also added comments to the code to clarify.

My forthcoming book includes detailed explanations. Here is a preview of the first chapters: https://danderzei.storageshare.net/s/LkfHwmy5KdFBimP
