### ISSUE TITLE
use custom XDG user directories 

### ISSUE THREAD

**Issue by HiTuX** [pprevos/emacs-writing-studio#9]
Helllo Peter, 
Thank you so much for creating and maintaining such a "lucid" configuration.

I have customized XDG user dirs names, e.g. `Documents` is `docs`, `Downloads` is `net`, `Videos` is `vids`, `Templates` is `docs/templates`, etc ... 
Thus, when using your config, some packages like `denote` and `elfeed` create `Documents` folder in my home and put their files there. 
I can change that in `ews.el` and `init.el`, However I think it would be nice if you make your config more general and reckon locale names by using `xdg-user-dir` buil-in function instead of hard code it: 
``` elisp
(xgd-user-dir "DOCUMENTS")
```
retruns
```
/home/USER/docs
```

**Comment by pprevos** [comment]
Hi @HiTuX ,

The `denote-directory` variable is not configured in the EWS init file. In the forthcoming EWS book I am recommending to use `M-x customize-variable RET denote directory` (website still needs updating).  EWS will store this config in `custom.el`.

The default for `denote-directory` is hard-coded in the Denote package. Perhaps raise an issue with Prot on `https://github.com/protesilaos/denote` to make it more malleable.

Check the customizable variables for EWS with `M-x customize-group RET ews` and set them accordingly.

**Comment by HiTuX** [comment]
I will raise the issue with pro.

I try my best to avoid `customize-group` as it creates `custom.el` or customize section that is advised to NOT edit manually. I prefer to edit `init.el` file directly.

**Comment by pprevos** [comment]
That is what I do. However, I designed EWS for beginners and wrote it to leverage the customisation tools.

EWS is not a maintained config like Doom. It is designed to learn Emacs, so just modify the init file to meet your needs.

**Comment by HiTuX** [comment]
`denote-directory` can be set with `(setq denote-directory "~/docs/denotes/")`. The issue hold with `elfeed` and `ews-bibtex-directory`.

**Comment by pprevos** [comment]
Feel free to submit a pull request for `init.el` and `ews.el` (so you get the credit) or would you like me to make the changes?

**Comment by HiTuX** [comment]
After rethinking about it, I hesitate to submit a pull request. 

Actually Denote package implemented the `xdg` feature in [version 0.5.0](https://protesilaos.com/emacs/denote-changelog#h:efa3049e-f1fa-48ff-af7d-d16edc677704), then removed it in [version 2.0.0](https://protesilaos.com/emacs/denote-changelog#h:918087e6-8cd5-4d4f-a11a-b465dcbd9fe3). 

The motive for the removal is explained by Prot:

> The reason is that XDG is a Linux standard that does not work on other operating systems, according to private feedback I received. 

Thus, to keep EWS usable for all people on other OS, I abstain from introducing `xdg-user-dir`.
sorry for inconvenience.

**Comment by pprevos** [comment]
No worries, I learnt something new :)
